language: node_js
node_js:
- '12'
env:
  global:
  - secure: IwFlWebIo6MKAftDCYevE5k+aOqAvVUlSSudd+ADaGYMwSGHlTcACL4djGpPiEBeuTv+AALxToGmTqNj2J3YZBfVyH8ausS9xVdHPC0N3e8N6oqjdxcSMDpoyQBV7CYdl5vBNLIiexpsGepTQWinPOM2bwcmLV6nUE1QY/62Jy0yfGOiMROE9RM3OvISKj87mAxXYoKQP9ySuIjhOWaAXrZDBDQ3GrtlDO3PHZ/RK9uX+JlzUyhtQ8C6dtR+ETx9Awzi2h17pVkkom20XqLsWuIS303nusB2BDDCYlAWY6qocfamyfNuhL6P2+FB2fSmTCCCkUZlsA8lCXxAyWu7fPhJW9YmlGwUzbo4fW3CUeODvykqZFyuRMJDBWIsAtTJHYoen2wE7Ly4v59rZjXyZw1sEbOtGU6UVFvRYB2+seJE3Kb5k/tRHH7P8JL4RayYRg8SbU5rKmGNuDMxrI6Y25fT9yK1TiO7q34PHS/OI0wszqdAFBvtlB3Yb6Kb9SatqQED+POJ1gsE0Ra7xiib9BmorFDP5WtxeWDHbKFWdOhT1Re8kXEApvl5KucztCJ9iuZWdkt9/pkK9DKpoo1FZI+6dBghzJhozvEgOum3uwjVUb0exFrZi7PY7BsBUV14PqIWLbbGVXAh/8ctXhCjyGqRkXXeDFmW3M+LlDTIV7w=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5ac8eb3c5228_key -iv $encrypted_5ac8eb3c5228_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
