language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    - secure: "IIujjX9uSbvrGrFptM9LIOkLJK0vXB4aFI9nSwkkXIu329PJ9z5IOkEwRUZyW9YpRlGTc9alUs3BTcTegZwyZyDTsqVRuiqHILN3iFKmonMz++rWmRwMiNZskd6+29kUqMGJmuYcqSWZf074AJhsDv7cA9YXmsi5wwNZ2sgkrQ2eOJMBKmNOBYXGz5JEMiOBHu+/TcMHZjDJnsw15EloxNpdXMrV7Ix6w8bluQzkXye3bKsoM21kCzKXR9q5nbF8OoS1H/t6jVSDoAfY9vFnJlu6Nj1OMoFO7WAKsyqsxuvZ7NpRezfYOdC7PB29wwOyYrv7Ma1LOSJ2c7gs/CajISv4bqUQZwuy+YQJZ3QaAqRzkLu5UBVJTJetLzdDfqI/zrqlJMj7nuDlukhY3S45Zl+UiGDt9s7QDhLw1s0FKgXPw1uZMSeYxlx4pt3GN8s1hlM0Cf+a9lzn3sRdP3Ph6aMTSg8ZP70y3upj7n9wGCuFOmNwTr5AljlzKoT3w/iJ9ia9Toa08nLy9TRlSh0fOF4MWwiqwpukM/KMihyMx82dVGrEuP3FmqcdsD57w597bhLviv+xyzZAKcDL1p/DkWQLlkSftP89QhJeXuMVct2YrmlF5D0qkfjDpAwtHa8t3rhqcHAnErEvbvzt2sawLWayGM+YwKxmqcWM4cSHvPs="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-harmonie
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-harmonie
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
